name: Cache Demo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: prime-cache-650309a
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo-deps
          key: cache-650309a

      - name: Show cache hit or miss
        run: echo "Cache hit: ${{ steps.prime-cache-650309a.outputs.cache-hit }}"
