name: Cache Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/mydeps
          key: cache-650309a

      - name: Show cache hit or miss
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Say Hello
        run: echo "Hello, world!"
