name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Cache uv dependencies
        id: prime-cache-650309a
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: cache-650309a

      - name: prime-cache-650309a
        run: |
          if [[ "${{ steps.prime-cache-650309a.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Cache will be saved."
          fi
